// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LoadingController from "./loading_controller"
application.register("loading", LoadingController)

import NestedFormController from "./nested_form_controller"
application.register("nested-form", NestedFormController)

import ProductController from "./product_controller"
application.register("product", ProductController)

import RakutenSearchController from "./rakuten_search_controller"
application.register("rakuten-search", RakutenSearchController)

import RemoteModalController from "./remote_modal_controller"
application.register("remote-modal", RemoteModalController)

import TabStatusController from "./tab_status_controller"
application.register("tab-status", TabStatusController)
